In [1]:
import numpy as np

In [5]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [21]:
a_centered = np.transpose(np.array([np.transpose(a)[np.transpose(a) < 4] - mean_a[0], np.transpose(a)[np.transpose(a) > 4] - mean_a[1]]))
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [30]:
a_centered = np.transpose(np.array([np.transpose(a)[np.transpose(a) < 4] - mean_a[0], np.transpose(a)[np.transpose(a) > 4] - mean_a[1]]))
a_centered_sp = np.transpose(a_centered)[0] @ np.transpose(a_centered)[1]
x = a_centered_sp / (a_centered.shape[0] - 1)
x


2.0

In [33]:
d = np.cov(np.transpose(a))
d

array([[1. , 2. ],
       [2. , 4.3]])